#! /bin/sh
# /etc/init.d/jagsilvafotos

### BEGIN INIT INFO
# Provides: jagsilvafotos
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Simple script to start a program at boot
# Description: A simple script from www.stuffaboutcode.com which will
# start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific
# functions when asked to by the system
case "$1" in
  start)
    echo "++++++++++++++++++++++++++++++++++++++++++++\nArrancar servidor de fotos"
    # run application you want to start
    sudo python /home/pi/py/servidordefotos01.py &
    sudo python /home/pi/py/servidor.py &
    ;;
  stop)
    echo "Parar o servidor de fotos"
    # kill application you want to stop
    killall servidordefotos
    killall servidor
    ;;
  *)
    echo "Usage: /etc/init.d/jagsilva-fotos {start|stop}"
    exit 1
    ;; esac
exit 0
